ALTER DATABASE [MyData] MODIFY FILE (NAME = 'MyData', SIZE = 154816 KB)
GO
ALTER TABLE [dbo].[Customer_lookup]
	ADD
	PRIMARY KEY
	NONCLUSTERED
	([PKey])
	ON [PRIMARY]
GO

SET ANSI_NULLS ON
SET ANSI_PADDING ON
GO

CREATE FUNCTION [dbo].[UDF_GetCustomers]
( )
AS
BEGIN
DECLARE @Total int
SELECT TOP 1 @Total =MaxCustomers FROM CustomerList
SET QUOTED_IDENTIFIER ON
RETURN (@Total)
END

